##Installation
##CRAN: https://cran.r-project.org/index.html 
##Open R Gui or Rstudio
![Picture1.png](R_5352_2020/Picture1.png)
![Picture2.jpg](R_5352_2020/Picture2.jpg)

In [2]:
##Data Structures
print("1.Vector")
c(1,2,3)
c(1,2,3) + c(4,5,6)
c(3,2) + c(1,2,3)
X <- c("a","b","c")
X
Y <- c(42, "Statistics", TRUE)
##check the Data type of Y
Y
c(42, FALSE)
seq(1,5,1)
rev(c(1,2,3))
rep("SBMI",5)
runif(10)
rnorm(15)
Z = c(X,Y)
length(Z)
mode(Z)
print("2.Subsetting of Vectors")
x = c(1, 3, 5, 7, 8, 9)
x[1]
x[3]
x[1:3]
x[c(1,4,5)]
x[-2]
z = c(TRUE, TRUE, FALSE, TRUE, TRUE, FALSE)
x[z]
x[4]
x[-3]
x[2:5]
x[7]
x["A"]
x[c(1,5)]
x[x>3]
x[x >3 & x<5]
print("3.Vectorization")
x = 1:10
x > 3
x + 1
2 * x
2^x
x == 3 | x != 3
x == 3 & x != 3
x == 3 && x != 3
sqrt(x)
log(x)
log10(x)
log2(x)
sum(x > 3)
as.numeric(x > 3)





[1] "1.Vector"


[1] 1 2 3

[1] 5 7 9

Warning message in c(3, 2) + c(1, 2, 3):
"longer object length is not a multiple of shorter object length"


[1] 4 4 6

[1] "a" "b" "c"

[1] "42"         "Statistics" "TRUE"

[1] 42  0

[1] 1 2 3 4 5

[1] 3 2 1

[1] "SBMI" "SBMI" "SBMI" "SBMI" "SBMI"

[1] 0.76187099 0.54798184 0.55331689 0.70530873 0.49361537 0.13268270
 [7] 0.26686839 0.07535693 0.67839162 0.33514222

[1] -0.0243817  0.6281150  0.4675496 -0.7094198 -1.4568930  0.7252565
 [7]  0.1887841 -0.4280505 -0.3012439  0.6440480 -0.4142996 -1.1422421
[13]  0.3625786  1.7035333 -1.0304466

[1] 6

[1] "character"

[1] "2.Subsetting of Vectors"


[1] 1

[1] 5

[1] 1 3 5

[1] 1 7 8

[1] 1 5 7 8 9

[1] 1 3 7 8

[1] 7

[1] 1 3 7 8 9

[1] 3 5 7 8

[1] NA

[1] NA

[1] 1 8

[1] 5 7 8 9

numeric(0)

[1] "3.Vectorization"


[1] FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

[1]  2  3  4  5  6  7  8  9 10 11

[1]  2  4  6  8 10 12 14 16 18 20

[1]    2    4    8   16   32   64  128  256  512 1024

[1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

[1] FALSE

[1] 1.000000 1.414214 1.732051 2.000000 2.236068 2.449490 2.645751 2.828427
 [9] 3.000000 3.162278

[1] 0.0000000 0.6931472 1.0986123 1.3862944 1.6094379 1.7917595 1.9459101
 [8] 2.0794415 2.1972246 2.3025851

[1] 0.0000000 0.3010300 0.4771213 0.6020600 0.6989700 0.7781513 0.8450980
 [8] 0.9030900 0.9542425 1.0000000

[1] 0.000000 1.000000 1.584963 2.000000 2.321928 2.584963 2.807355 3.000000
 [9] 3.169925 3.321928

[1] 7

[1] 0 0 0 1 1 1 1 1 1 1

In [3]:
##Data Type
print("1.Character")
print("First command line")
print("Hello World!")
"A"
#A
mode("A")
is.character("A")
print("2.Numeric")
1
is.numeric(1)
1.0
is.numeric(1.0)
24.50
print("3.Integer as a special Numeric")
1L
is.integer(1L)
is.numeric(1L)
mode(1L)
2.50L
is.integer(2.5L)
print("4.Complex")
4 + 2i
is.complex(2+1i)
print("5.Logical and Boolean operater")
1 > 0
1 < 0
1 >= 0
x = 1
x == 1
y = 1 
x != y
!x
x|y
TRUE && FALSE
c(TRUE,TRUE) && c(FALSE,FALSE)
c(TRUE,TRUE) & c(FALSE,FALSE)
is.na(c(1,NA,"NULL","na",""))
print("6.Factor")
factors = as.factor(c("A","B","C"))
levels(factors)
factors



[1] "1.Character"
[1] "First command line"
[1] "Hello World!"


[1] "A"

[1] "character"

[1] TRUE

[1] "2.Numeric"


[1] 1

[1] TRUE

[1] 1

[1] TRUE

[1] 24.5

[1] "3.Integer as a special Numeric"


[1] 1

[1] TRUE

[1] TRUE

[1] "numeric"

[1] 2.5

[1] FALSE

[1] "4.Complex"


[1] 4+2i

[1] TRUE

[1] "5.Logical and Boolean operater"


[1] TRUE

[1] FALSE

[1] TRUE

[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

[1] FALSE

[1] FALSE

[1] FALSE FALSE

[1] FALSE  TRUE FALSE FALSE FALSE

[1] "6.Factor"


[1] "A" "B" "C"

[1] A B C
Levels: A B C

In [4]:
print("2.Matrix/array")
x = 1:9
X = matrix(x, nrow = 3, ncol = 3)
Y = matrix(x, nrow = 3, ncol = 3, byrow = TRUE)
X
Y
X[1, 2]
Y[1,]
Y[,2]
X[1,c(2:3)]
rbind(x, rev(x), rep(1, 9))
Z =rbind(x, rev(x), rep(1, 9))
Z
cbind(col_1 = x, col_2 = rev(x), col_3 = rep(1, 9))
##When using rbind and cbind you can specify “argument” names that will be used as column names.
x = 1:9
y = 9:1
X = matrix(x, 3, 3)
Y = matrix(y, 3, 3)
#Matrix calculation
X + Y
X - Y
X/Y
X*Y
X%*%Y
colSums(X)
rowSums(Y)
rowMeans(X)
colMeans(Y)
diag(X)

[1] "2.Matrix/array"


[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

[1] 4

[1] 1 2 3

[1] 2 5 8

[1] 4 7

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
x 1    2    3    4    5    6    7    8    9   
  9    8    7    6    5    4    3    2    1   
  1    1    1    1    1    1    1    1    1

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
x 1    2    3    4    5    6    7    8    9   
  9    8    7    6    5    4    3    2    1   
  1    1    1    1    1    1    1    1    1

col_1 col_2 col_3
 [1,] 1     9     1    
 [2,] 2     8     1    
 [3,] 3     7     1    
 [4,] 4     6     1    
 [5,] 5     5     1    
 [6,] 6     4     1    
 [7,] 7     3     1    
 [8,] 8     2     1    
 [9,] 9     1     1

[,1] [,2] [,3]
[1,] 10   10   10  
[2,] 10   10   10  
[3,] 10   10   10

[,1] [,2] [,3]
[1,] -8   -2   4   
[2,] -6    0   6   
[3,] -4    2   8

[,1]      [,2]      [,3]    
[1,] 0.1111111 0.6666667 2.333333
[2,] 0.2500000 1.0000000 4.000000
[3,] 0.4285714 1.5000000 9.000000

[,1] [,2] [,3]
[1,]  9   24   21  
[2,] 16   25   16  
[3,] 21   24    9

[,1] [,2] [,3]
[1,]  90  54   18  
[2,] 114  69   24  
[3,] 138  84   30

[1]  6 15 24

[1] 18 15 12

[1] 4 5 6

[1] 8 5 2

[1] 1 5 9

In [5]:
print("1.list")
x = list()
x[["BRCA_genes"]] = c("BRCA1", "BRCA2")
x[["LUAD_genes"]] = c("EGFR", "KRAS", "BRAF")
x
x[1]
x[[1]]
x[["BRCA_genes"]]
x$BRCA_genes



[1] "1.list"


$BRCA_genes
[1] "BRCA1" "BRCA2"

$LUAD_genes
[1] "EGFR" "KRAS" "BRAF"

$BRCA_genes
[1] "BRCA1" "BRCA2"

[1] "BRCA1" "BRCA2"

[1] "BRCA1" "BRCA2"

[1] "BRCA1" "BRCA2"

In [6]:
print("1.Data frame")
example_data = data.frame(x = seq(1,10,1),
                          y = c(rep("Hello", 9), "Goodbye"),
                          z = rep(c(TRUE, FALSE), 5))
example_data
#Unlike a list which has more flexibility, the elements of a data frame must all be vectors, and have the same length.
str(example_data)
nrow(example_data)
ncol(example_data)
dim(example_data)


[1] "1.Data frame"


x  y       z    
1   1 Hello    TRUE
2   2 Hello   FALSE
3   3 Hello    TRUE
4   4 Hello   FALSE
5   5 Hello    TRUE
6   6 Hello   FALSE
7   7 Hello    TRUE
8   8 Hello   FALSE
9   9 Hello    TRUE
10 10 Goodbye FALSE

'data.frame':	10 obs. of  3 variables:
 $ x: num  1 2 3 4 5 6 7 8 9 10
 $ y: Factor w/ 2 levels "Goodbye","Hello": 2 2 2 2 2 2 2 2 2 1
 $ z: logi  TRUE FALSE TRUE FALSE TRUE FALSE ...


[1] 10

[1] 3

[1] 10  3

In [7]:
print("Lab exercise: input and output")
#test data
#library("package")
getwd()
wd <- getwd()
#setwd(wd)
data(mtcars)
ls()
head(mtcars)
dim(mtcars)
#write.table(mtcars,file="mtcar.txt",row.names=TRUE,col.names=TRUE,sep=" ")
#read.delim("mtcar.txt",header=TRUE)
#save.image("5/15/2020.Rdata")
#load("5/15/2020.Rdata")

[1] "Lab exercise: input and output"


[1] "H:/"

[1] "example_data" "factors"      "mtcars"       "wd"           "x"           
 [6] "X"            "y"            "Y"            "z"            "Z"

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

[1] 32 11

![Picture3.png](R_5352_2020/Picture3.png)